---
galaxy_info:
  author: Ondrej Faměra
  description: pacemaker basic cluster role with fencing configuration (xvm, kdump, custom)
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 6
    - 7
    - 8
  - name: Fedora
    versions:
    - 28
    - 29
    - 30
  galaxy_tags:
  - clustering
  - pacemaker
dependencies:
  - { role: ondrejhome.pcs-modules-2 }
