---
- name: Install libselinux-python to work with SELinux setting
  yum:
    name: 'python-selinux'
    state: 'present'
  become: yes
  become_user: root
  when: not (ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8')
  

- name: Install Pacemaker cluster packages to all nodes
  yum:
    name: "{{ pacemaker_packages }}"
    state: 'latest'
  become: yes
  become_user: root

# - name: Install firewall packages
#   yum:
#     name: '{{ firewall_packages }}'
#     state: 'latest'
#   become: yes
#   become_user: root
#   when: cluster_firewall|bool

# - name: Install package(s) for fence_xvm
#   yum:
#     name: "{{ fence_xvm_packages }}"
#     state: 'latest'
#   become: yes
#   become_user: root
#   when: cluster_configure_fence_xvm|bool

# - name: Install package(s) for fence_kdump
#   yum:
#     name:  "{{ fence_kdump_packages }}"
#     state: 'latest'
#   become: yes
#   become_user: root
#   when: cluster_configure_fence_kdump|bool
